### ISSUE TITLE
Error creating new deals via API

### ISSUE THREAD

**Issue by AlCaughey** [basecrm/basecrm-php#21]
Not documented on the help page but you *must* enter a value when creating a new deal via the API... the documentation currently shows:
> $client = new \BaseCRM\Client(['accessToken' => '<YOUR_PERSONAL_ACCESS_TOKEN>']);
> $deal = $client->deals->create(['name' => 'Website redesign', 'contact_id' => $id]);

But, the second line should be:
> $deal = $client->deals->create(['name' => 'Website redesign', 'contact_id' => $id,  'value' => <amount|0> ]);

The offending code is on line #63 in `vendor\basecrm\basecrm-php\lib\DealsService.php:
> $attributes["value"] = Coercion::toStringValue($attributes['value']);

should be changed to:
> if (isset($attributes["value"])) $attributes["value"] = Coercion::toStringValue($attributes['value']);

**Comment by efedasz** [comment]
Hi @AlCaughey thanks for the note. It's fixed in version `1.3.1`.

**Comment by Frederick888** [comment]
@efedasz I can still reproduce this issue using `v1.4.0`. https://github.com/basecrm/basecrm-php/blob/v1.3.1/lib/DealsService.php#L63 doesn't seem to have a fix in place?
